### ISSUE TITLE
Map <ESC>  close_window?

### ISSUE THREAD

**Issue by hungrybirder** [npxbr/glow.nvim#13]
Hi,
Glow window can be closed by `q`. https://github.com/npxbr/glow.nvim/blob/main/lua/glow.lua#L129

Maybe it's a good idea of mapping `<ESC>` to close_window.

```lua
  api.nvim_buf_set_keymap(buf, "n", "<ESC>", ":lua require('glow').close_window()<cr>",
                          {noremap = true, silent = true})
```

**Comment by ellisonleao** [comment]
added in https://github.com/npxbr/glow.nvim/pull/12
