### ISSUE TITLE
highlights

### ISSUE THREAD

**Issue by 0xRZ** [npxbr/glow.nvim#16]
When i first opened glow floating window it looked like this 
![Screenshot_20210512_125503](https://user-images.githubusercontent.com/46892933/117956004-4c47d200-b321-11eb-8aab-8f6f9fcf826f.png)
By adjusting NormalFloat highlight group i can change background and border colors of a floating window, but i can not figure out how to change text color, can you advice me if possible how to change it?

**Comment by ellisonleao** [comment]
hey @0xRZ the floating window relies in your terminal color configs pretty much, but can you share a minimal config for investigation?

**Comment by 0xRZ** [comment]
nvim --version: NVIM v0.5.0-dev+1314-g7b0edaac5
and vimrc as:
```vim
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
        silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        autocmd VimEnter * PlugInstall --sync
endif

call plug#begin()
Plug 'npxbr/glow.nvim', {'do': 'git clone https://github.com/charmbracelet/glow.git && cd glow && go build && mv glow $HOME/go/bin','branch':'main'}
call plug#end()
```

i get badly distinguishable grey text in floating window that i would like to change
![Screenshot_20210512_153824](https://user-images.githubusercontent.com/46892933/117976169-1eba5300-b338-11eb-9901-7e06fa5c41ad.png)

And i can not understand what highlight group corresponds to it

**Comment by ellisonleao** [comment]
hey @0xRZ, glow is using a neovim terminal instance inside a buffer. Can you try calling glow command outside neovim and check if you have the same output?
