### ISSUE TITLE
:GlowInstall [Process exited 2]

### ISSUE THREAD

**Issue by lyonelz96** [npxbr/glow.nvim#17]
**Describe the bug**
I do :GlowInstall and it gives me an error
![image](https://user-images.githubusercontent.com/43832900/119768557-d1d19300-be86-11eb-9045-4b55528c67d5.png)

**To Reproduce**
Using the paq package manager

1. Go to init.lua
2. Add 
```lua
paq {'npxbr/glow.nvim', run=function() vim.cmd ':GlowInstall' end, branch='main'}
```
3. Do :PaqInstall
4. Get Error
5. Try doing :GlowInstall manually, still get error.

**Expected behavior**
Glow installs successfully!

**Additional context**
Neovim Version: NVIM v0.5.0-dev+1330
Distro: Arch Linux
Terminal: Windows Terminal (Using WSL2)

**Comment by ellisonleao** [comment]
hey @lyonelz96 can you show me the output for `uname -i` and `uname -s | tr "[:upper:]" "[:lower:]"` please?

**Comment by ellisonleao** [comment]
cool, thanks, it seems arch makes it harder to grab its name. Will think about a fix and push it.

**Comment by ellisonleao** [comment]
hey @lyonelz96 just pushed a fix, can you check if its working on your side please?

**Comment by lyonelz96** [comment]
I get this now:
![image](https://user-images.githubusercontent.com/43832900/120051409-8b974380-bfee-11eb-963c-77294ff0080a.png)

**Comment by ellisonleao** [comment]
new attempt @lyonelz96  hehe

**Comment by lyonelz96** [comment]
Haha, it works! Very cool, thank you! @ellisonleao
