### ISSUE TITLE
Packer problem

### ISSUE THREAD

**Issue by italoaa** [npxbr/glow.nvim#22]
![image](https://user-images.githubusercontent.com/72895337/122113206-64f74c00-cde7-11eb-8c96-e375efe7efc7.png)

I ran :PackerInstall and then when executing :GlowInstall it fails I suppose and show the above

this is on mac running fish and also in Iterm

**Comment by ellisonleao** [comment]
Looks like you have an issue with your locale value in your environment. Can you try:

```bash
$ export LANG=en_US.UTF-8
$ export LC_ALL=$LANG
```

and trying again please?

**Comment by italoaa** [comment]
i have this problem now
tar: Error opening archive: Unrecognized archive format

**Comment by ellisonleao** [comment]
@italoaa can you try again please?
