### ISSUE TITLE
Installation isn't working on macOS

### ISSUE THREAD

**Issue by ofsaleem** [npxbr/glow.nvim#23]
I've followed the instructions from the readme (using vim-plug) and installation fails:

```bash
tar: Error opening archive: Unrecognized archive format

[Process exited 1]
```

If I try to run :Glow after it says it's not installed, and to run :GlowInstall, which gives me the error above as well. I noticed locally in the folder I was in, there's a `glow.tar.gz` file, but it doesn't seem to be a proper tar file, hence the error:

```bash
~ ls -la
-rw-r--r--  1 omar  staff     9B Jul  1 13:42 glow.tar.gz
```

```bash
~ file glow.tar.gz
glow.tar.gz: ASCII text, with no line terminators
```

```bash
~ cat glow.tar.gz
Not Found%
```

**Comment by ellisonleao** [comment]
hey @ofsaleem I just pushed a possible fix, can you test again please? unfortunately I don't have OSX available here for a real test. Let me know if that fixes the problem

**Comment by ofsaleem** [comment]
same behavior unfortunately :(

**Comment by ellisonleao** [comment]
@ofsaleem can you output the following commands please?

```
uname -a
```

and

```
uname -p
```

**Comment by ofsaleem** [comment]
```bash
 ~ uname -a
Darwin omar-saleem-mbp.workdomain 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64
 ~ uname -p
arm
```

**Comment by bitsapien** [comment]
I'm on a Mac from 2018, this fails for me too.

**Comment by ellisonleao** [comment]
@ofsaleem can you try again please?

**Comment by ofsaleem** [comment]
calling GlowInstall gives me: 

```bash
  LICENSE: Can't create 'LICENSE'
  README.md: Can't create 'README.md'
  glow: Can't create 'glow'
  tar: Error exit delayed from previous errors.
  
  [Process exited 1]
```
glow.tar.gz is still in the directory, but it looks like a proper tar file now, as its 5.6M and i was able to manually untar it. doing so doesn't help with the :GlowInstall however

**Comment by ellisonleao** [comment]
@ofsaleem what is the `tar` command you are trying? The basic flow for the current script is to grab a tar from github releases page, untar it and move the glow binary to $GOPATH/bin. You check check it [here](https://github.com/npxbr/glow.nvim/blob/main/lua/glow.lua#L55)

**Comment by ofsaleem** [comment]
i was just doing `tar -xf glow.tar.gz` but i see the issue, i don't have $GOPATH set. I set that, and added $GOPATH/bin to my $PATH, and now everything works. without $GOPATH set your command was failing since there was no directory to extract to. thanks! maybe something should be put in the readme so people know to have go stuff set in their environment, i had no idea it was gonna be needed for this lovely plugin

**Comment by ellisonleao** [comment]
cool, i will add that env var check in the install script to avoid more issues
