### ISSUE TITLE
Question about hover

### ISSUE THREAD

**Issue by Shatur95** [npxbr/glow.nvim#3]
Hi! Thank you for the aweome plugin. I have a question about usage. Is it possible to use to for hover and diagnostic LSP messages? It uses markdown, but built-in Markdown renderer in Neovim is not good :)

**Comment by ellisonleao** [comment]
the tool we use in the plugin accepts inputs from stdin, maybe that can be a new command that wraps a diagnostic message using the command.. I need to check how we could maybe call a function from glow.nvim lib to a custom diagnostic handler function. I am open to ideas !
