### ISSUE TITLE
better handling of glow installation

### ISSUE THREAD

**Issue by ellisonleao** [npxbr/glow.nvim#8]
Current instalation is broken. The basic steps now are:

```
git clone https://github.com/charmbracelet/glow.git
cd glow
go build && mv glow $GOPATH/bin
```

**Comment by Marko-Sanchez** [comment]
As of 7/18/2021, I got a permission denied error when trying to `:GlowInstall` the tar file get's downloaded but I needed to run with sudo permissions on it and fallowed the steps in `glow.lua`:
 `sudo tar -zxf glow.tar.gz -C "$GOPATH/bin"`
 `[ -f "glow.tar.gz" ] && rm "glow.tar.gz" `

**Comment by ellisonleao** [comment]
hey @Marko-Sanchez what OS are you on?
