### ISSUE TITLE
Toggle the glow window?

### ISSUE THREAD

**Issue by pschmitt** [npxbr/glow.nvim#9]
Hi, cool plugin!

Is there a way to toggle the preview window?

**Comment by ellisonleao** [comment]
hey @pschmitt not sure what you mean by "preview window". Current `:Glow`  command already pops a floating window with the output. Can you clarify please?

**Comment by pschmitt** [comment]
Sure, sure what I want is to be able to toggle the terminal window that displays glow.

Workflow-wise this would look like that:

- call `ToggleGlow()` -> show the preview window if not currently displayed, else hide it (as if the user pressed `q`)

**Comment by ellisonleao** [comment]
Will definitely think in a possible func alongside with a mapping for this.

**Comment by ellisonleao** [comment]
@pschmitt just pushed the feature, using `:Glow` as a toggle command right now. Let me know if that worked for you
